name: Build Signed Release APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode Keystore
        run: |
          mkdir -p app
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/release-key.jks

      - name: ðŸ“¦ Get versionName from build.gradle.kts
        id: version
        run: |
          VERSION_NAME=$(grep -oP 'versionName\s*=\s*"\K[0-9]+\.[0-9]+\.[0-9]+' app/build.gradle.kts)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Signed Release APK
        run: ./gradlew clean assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Signed APK (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error

      - name: Create GitHub Release & Upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release.apk
          name: v${{ env.VERSION_NAME }}
          body: |
            This is a new release!
            See the attached asset for more details.
          draft: false
          prerelease: false
          generate_release_notes: true
          tag_name: v${{ env.VERSION_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update GitHub Repo Website URL
        run: |
          curl -X PATCH \
          -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }} \
          -d "{\"homepage\":\"https://github.com/${{ github.repository }}/releases/download/v${{ env.VERSION_NAME }}/app-release.apk\"}"
